In [1]:
with open("api_key.txt") as file:
    API_key = file.read()

In [3]:
API_key = API_key.strip()

In [4]:
API_key

'N0YVA5RVTIR2D1OL'

In [2]:
from alpha_vantage.timeseries import TimeSeries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import io

In [35]:
pd.options.display.max_columns = None

In [10]:
ts1 = TimeSeries(key=API_key)

In [11]:
ts1.get_monthly('AAPL')

({'2026-04-23': {'1. open': '254.0800',
   '2. high': '275.7700',
   '3. low': '245.7000',
   '4. close': '273.4300',
   '5. volume': '665999564'},
  '2026-03-31': {'1. open': '262.4100',
   '2. high': '266.5300',
   '3. low': '245.5100',
   '4. close': '253.7900',
   '5. volume': '900035757'},
  '2026-02-27': {'1. open': '260.0300',
   '2. high': '280.9050',
   '3. low': '255.4500',
   '4. close': '264.1800',
   '5. volume': '988325816'},
  '2026-01-30': {'1. open': '272.2550',
   '2. high': '277.8400',
   '3. low': '243.4200',
   '4. close': '259.4800',
   '5. volume': '1036170325'},
  '2025-12-31': {'1. open': '278.0100',
   '2. high': '288.6200',
   '3. low': '266.9500',
   '4. close': '271.8600',
   '5. volume': '922283649'},
  '2025-11-28': {'1. open': '270.4200',
   '2. high': '280.3800',
   '3. low': '265.3200',
   '4. close': '278.8500',
   '5. volume': '876481453'},
  '2025-10-31': {'1. open': '255.0400',
   '2. high': '277.3200',
   '3. low': '244.0000',
   '4. close': '270.3700',
   '5. volume': '1097142365'},
  '2025-09-30': {'1. open': '229.2500',
   '2. high': '257.6000',
   '3. low': '225.9500',
   '4. close': '254.6300',
   '5. volume': '1265170319'},
  '2025-08-29': {'1. open': '210.8650',
   '2. high': '235.1200',
   '3. low': '201.5000',
   '4. close': '232.1400',
   '5. volume': '1218125232'},
  '2025-07-31': {'1. open': '206.6650',
   '2. high': '216.2300',
   '3. low': '206.1401',
   '4. close': '207.5700',
   '5. volume': '1079935847'},
  '2025-06-30': {'1. open': '200.2800',
   '2. high': '207.3900',
   '3. low': '195.0700',
   '4. close': '205.1700',
   '5. volume': '1100504397'},
  '2025-05-30': {'1. open': '209.0800',
   '2. high': '214.5600',
   '3. low': '193.2500',
   '4. close': '200.8500',
   '5. volume': '1195889556'},
  '2025-04-30': {'1. open': '219.8050',
   '2. high': '225.1900',
   '3. low': '169.2101',
   '4. close': '212.5000',
   '5. volume': '1607318483'},
  '2025-03-31': {'1. open': '241.7900',
   '2. high': '244.0272',
   '3. low': '208.4200',
   '4. close': '222.1300',
   '5. volume': '1114686136'},
  '2025-02-28': {'1. open': '229.9900',
   '2. high': '250.0000',
   '3. low': '225.7000',
   '4. close': '241.8400',
   '5. volume': '862317019'},
  '2025-01-31': {'1. open': '248.9300',
   '2. high': '249.1000',
   '3. low': '219.3800',
   '4. close': '236.0000',
   '5. volume': '1200291603'},
  '2024-12-31': {'1. open': '237.2700',
   '2. high': '260.1000',
   '3. low': '237.1600',
   '4. close': '250.4200',
   '5. volume': '977942014'},
  '2024-11-29': {'1. open': '220.9650',
   '2. high': '237.8100',
   '3. low': '219.7100',
   '4. close': '237.3300',
   '5. volume': '891640714'},
  '2024-10-31': {'1. open': '229.5200',
   '2. high': '237.4900',
   '3. low': '221.3300',
   '4. close': '225.9100',
   '5. volume': '930835961'},
  '2024-09-30': {'1. open': '228.5500',
   '2. high': '233.0900',
   '3. low': '213.9200',
   '4. close': '233.0000',
   '5. volume': '1231814423'},
  '2024-08-30': {'1. open': '224.3700',
   '2. high': '232.9200',
   '3. low': '196.0000',
   '4. close': '229.0000',
   '5. volume': '1122666993'},
  '2024-07-31': {'1. open': '212.0900',
   '2. high': '237.2300',
   '3. low': '211.9200',
   '4. close': '222.0800',
   '5. volume': '1153193377'},
  '2024-06-28': {'1. open': '192.9000',
   '2. high': '220.2000',
   '3. low': '192.1500',
   '4. close': '210.6200',
   '5. volume': '1723984420'},
  '2024-05-31': {'1. open': '169.5800',
   '2. high': '193.0000',
   '3. low': '169.1100',
   '4. close': '192.2500',
   '5. volume': '1336570142'},
  '2024-04-30': {'1. open': '171.1900',
   '2. high': '178.3600',
   '3. low': '164.0750',
   '4. close': '170.3300',
   '5. volume': '1240410671'},
  '2024-03-28': {'1. open': '179.5500',
   '2. high': '180.5300',
   '3. low': '168.4900',
   '4. close': '171.4800',
   '5. volume': '1430780147'},
  '2024-02-29': {'1. open': '183.9850',
   '2. high': '191.0500',
   '3. low': '179.2500',
   '4. close': '180.7500',
   '5. volume': '1161711745'},
  '2024-01-31': {'1. open': '187.1500',
   '2. high': '196.3800',
   '3. low': '180.1700',
   '4. close': '184.4000',
   '5. volume': '1187139861'},
  '2023-12-29': {'1. open': '190.3300',
   '2. high': '199.6200',
   '3. low': '187.4511',
   '4. close': '192.5300',
   '5. volume': '1062317718'},
  '2023-11-30': {'1. open': '171.0000',
   '2. high': '192.9300',
   '3. low': '170.1200',
   '4. close': '189.9500',
   '5. volume': '1099760711'},
  '2023-10-31': {'1. open': '171.2200',
   '2. high': '182.3400',
   '3. low': '165.6700',
   '4. close': '170.7700',
   '5. volume': '1172845791'},
  '2023-09-29': {'1. open': '189.4850',
   '2. high': '189.9800',
   '3. low': '167.6200',
   '4. close': '171.2100',
   '5. volume': '1337873796'},
  '2023-08-31': {'1. open': '196.2350',
   '2. high': '196.7300',
   '3. low': '171.9600',
   '4. close': '187.8700',
   '5. volume': '1323817340'},
  '2023-07-31': {'1. open': '193.7800',
   '2. high': '198.2300',
   '3. low': '186.6000',
   '4. close': '196.4500',
   '5. volume': '996368613'},
  '2023-06-30': {'1. open': '177.7000',
   '2. high': '194.4800',
   '3. low': '176.9306',
   '4. close': '193.9700',
   '5. volume': '1297863403'},
  '2023-05-31': {'1. open': '169.2800',
   '2. high': '179.3500',
   '3. low': '164.3100',
   '4. close': '177.2500',
   '5. volume': '1275052503'},
  '2023-04-28': {'1. open': '164.2700',
   '2. high': '169.8500',
   '3. low': '159.7800',
   '4. close': '169.6800',
   '5. volume': '967580718'},
  '2023-03-31': {'1. open': '146.8300',
   '2. high': '165.0000',
   '3. low': '143.9000',
   '4. close': '164.9000',
   '5. volume': '1520461315'},
  '2023-02-28': {'1. open': '143.9700',
   '2. high': '157.3800',
   '3. low': '141.3200',
   '4. close': '147.4100',
   '5. volume': '1307294493'},
  '2023-01-31': {'1. open': '130.2800',
   '2. high': '147.2300',
   '3. low': '124.1700',
   '4. close': '144.2900',
   '5. volume': '1443652725'},
  '2022-12-30': {'1. open': '148.2100',
   '2. high': '150.9199',
   '3. low': '125.8700',
   '4. close': '129.9300',
   '5. volume': '1675731304'},
  '2022-11-30': {'1. open': '155.0800',
   '2. high': '155.4500',
   '3. low': '134.3800',
   '4. close': '148.0300',
   '5. volume': '1724948219'},
  '2022-10-31': {'1. open': '138.2100',
   '2. high': '157.5000',
   '3. low': '134.3700',
   '4. close': '153.3400',
   '5. volume': '1868381344'},
  '2022-09-30': {'1. open': '156.6400',
   '2. high': '164.2600',
   '3. low': '138.0000',
   '4. close': '138.2000',
   '5. volume': '2083968147'},
  '2022-08-31': {'1. open': '161.0100',
   '2. high': '176.1500',
   '3. low': '157.1400',
   '4. close': '157.2200',
   '5. volume': '1509735435'},
  '2022-07-29': {'1. open': '136.0400',
   '2. high': '163.6300',
   '3. low': '135.6600',
   '4. close': '162.5100',
   '5. volume': '1447364668'},
  '2022-06-30': {'1. open': '149.9000',
   '2. high': '151.7400',
   '3. low': '129.0400',
   '4. close': '136.7200',
   '5. volume': '1749297959'},
  '2022-05-31': {'1. open': '156.7100',
   '2. high': '166.4800',
   '3. low': '132.6100',
   '4. close': '148.8400',
   '5. volume': '2400305601'},
  '2022-04-29': {'1. open': '174.0300',
   '2. high': '178.4900',
   '3. low': '155.3800',
   '4. close': '157.6500',
   '5. volume': '1683547838'},
  '2022-03-31': {'1. open': '164.6950',
   '2. high': '179.6100',
   '3. low': '150.1000',
   '4. close': '174.6100',
   '5. volume': '2171827429'},
  '2022-02-28': {'1. open': '174.0100',
   '2. high': '176.6500',
   '3. low': '152.0000',
   '4. close': '165.1200',
   '5. volume': '1628570227'},
  '2022-01-31': {'1. open': '177.8300',
   '2. high': '182.9400',
   '3. low': '154.7000',
   '4. close': '174.7800',
   '5. volume': '2106513962'},
  '2021-12-31': {'1. open': '167.4800',
   '2. high': '182.1300',
   '3. low': '157.8000',
   '4. close': '177.5700',
   '5. volume': '2443227128'},
  '2021-11-30': {'1. open': '148.9850',
   '2. high': '165.7000',
   '3. low': '147.4800',
   '4. close': '165.3000',
   '5. volume': '1688864233'},
  '2021-10-29': {'1. open': '141.9000',
   '2. high': '153.1650',
   '3. low': '138.2700',
   '4. close': '149.8000',
   '5. volume': '1565079040'},
  '2021-09-30': {'1. open': '152.8300',
   '2. high': '157.2600',
   '3. low': '141.2700',
   '4. close': '141.5000',
   '5. volume': '1797948421'},
  '2021-08-31': {'1. open': '146.3600',
   '2. high': '153.4900',
   '3. low': '144.5000',
   '4. close': '151.8300',
   '5. volume': '1462773381'},
  '2021-07-30': {'1. open': '136.6000',
   '2. high': '150.0000',
   '3. low': '135.7600',
   '4. close': '145.8600',
   '5. volume': '1916751489'},
  '2021-06-30': {'1. open': '125.0800',
   '2. high': '137.4100',
   '3. low': '123.1300',
   '4. close': '136.9600',
   '5. volume': '1606114354'},
  '2021-05-28': {'1. open': '132.0400',
   '2. high': '134.0700',
   '3. low': '122.2500',
   '4. close': '124.6100',
   '5. volume': '1711935110'},
  '2021-04-30': {'1. open': '123.6600',
   '2. high': '137.0700',
   '3. low': '122.4900',
   '4. close': '131.4600',
   '5. volume': '1889956694'},
  '2021-03-31': {'1. open': '123.7500',
   '2. high': '128.7200',
   '3. low': '116.2100',
   '4. close': '122.1500',
   '5. volume': '2650845211'},
  '2021-02-26': {'1. open': '133.7500',
   '2. high': '137.8770',
   '3. low': '118.3900',
   '4. close': '121.2600',
   '5. volume': '1825486961'},
  '2021-01-29': {'1. open': '133.5200',
   '2. high': '145.0900',
   '3. low': '126.3820',
   '4. close': '131.9600',
   '5. volume': '2239366098'},
  '2020-12-31': {'1. open': '121.0100',
   '2. high': '138.7890',
   '3. low': '120.0100',
   '4. close': '132.6900',
   '5. volume': '2319687808'},
  '2020-11-30': {'1. open': '109.1100',
   '2. high': '121.9900',
   '3. low': '107.3200',
   '4. close': '119.0500',
   '5. volume': '2122724412'},
  '2020-10-30': {'1. open': '117.6400',
   '2. high': '125.3900',
   '3. low': '107.7200',
   '4. close': '108.8600',
   '5. volume': '2895317580'},
  '2020-09-30': {'1. open': '132.7600',
   '2. high': '137.9800',
   '3. low': '103.1000',
   '4. close': '115.8100',
   '5. volume': '3886793083'},
  '2020-08-31': {'1. open': '432.8000',
   '2. high': '515.1400',
   '3. low': '126.0000',
   '4. close': '129.0400',
   '5. volume': '1184207050'},
  '2020-07-31': {'1. open': '365.1200',
   '2. high': '425.6600',
   '3. low': '356.5800',
   '4. close': '425.0400',
   '5. volume': '755162226'},
  '2020-06-30': {'1. open': '317.7500',
   '2. high': '372.3800',
   '3. low': '317.2100',
   '4. close': '364.8000',
   '5. volume': '810900890'},
  '2020-05-29': {'1. open': '286.2500',
   '2. high': '324.2400',
   '3. low': '285.8500',
   '4. close': '317.9400',
   '5. volume': '701660022'},
  '2020-04-30': {'1. open': '246.5000',
   '2. high': '294.5300',
   '3. low': '236.9000',
   '4. close': '293.8000',
   '5. volume': '816530808'},
  '2020-03-31': {'1. open': '282.2800',
   '2. high': '304.0000',
   '3. low': '212.6100',
   '4. close': '254.2900',
   '5. volume': '1570331732'},
  '2020-02-28': {'1. open': '304.3000',
   '2. high': '327.2200',
   '3. low': '256.3700',
   '4. close': '273.3600',
   '5. volume': '755223231'},
  '2020-01-31': {'1. open': '296.2400',
   '2. high': '327.8500',
   '3. low': '292.7500',
   '4. close': '309.5100',
   '5. volume': '734044103'},
  '2019-12-31': {'1. open': '267.2700',
   '2. high': '293.9700',
   '3. low': '256.2900',
   '4. close': '293.6500',
   '5. volume': '598871365'},
  '2019-11-29': {'1. open': '249.5400',
   '2. high': '268.0000',
   '3. low': '249.1600',
   '4. close': '267.2500',
   '5. volume': '448922253'},
  '2019-10-31': {'1. open': '225.0700',
   '2. high': '249.7500',
   '3. low': '215.1300',
   '4. close': '248.7600',
   '5. volume': '621478768'},
  '2019-09-30': {'1. open': '206.4300',
   '2. high': '226.4200',
   '3. low': '204.2200',
   '4. close': '223.9700',
   '5. volume': '547408488'},
  '2019-08-30': {'1. open': '213.9000',
   '2. high': '218.0300',
   '3. low': '192.5800',
   '4. close': '208.7400',
   '5. volume': '683515746'},
  '2019-07-31': {'1. open': '203.1700',
   '2. high': '221.3700',
   '3. low': '198.4100',
   '4. close': '213.0400',
   '5. volume': '473957094'},
  '2019-06-28': {'1. open': '175.6000',
   '2. high': '201.5700',
   '3. low': '170.2700',
   '4. close': '197.9200',
   '5. volume': '515218768'},
  '2019-05-31': {'1. open': '209.8800',
   '2. high': '215.3100',
   '3. low': '174.9900',
   '4. close': '175.0700',
   '5. volume': '739456573'},
  '2019-04-30': {'1. open': '191.6400',
   '2. high': '208.4800',
   '3. low': '188.3800',
   '4. close': '200.6700',
   '5. volume': '506117812'},
  '2019-03-29': {'1. open': '174.2800',
   '2. high': '197.6900',
   '3. low': '169.5000',
   '4. close': '189.9500',
   '5. volume': '650981384'},
  '2019-02-28': {'1. open': '166.9600',
   '2. high': '175.8700',
   '3. low': '165.9300',
   '4. close': '173.1500',
   '5. volume': '472540723'},
  '2019-01-31': {'1. open': '154.8900',
   '2. high': '169.0000',
   '3. low': '142.0000',
   '4. close': '166.4400',
   '5. volume': '828099179'},
  '2018-12-31': {'1. open': '184.4600',
   '2. high': '184.9400',
   '3. low': '146.5900',
   '4. close': '157.7400',
   '5. volume': '898917007'},
  '2018-11-30': {'1. open': '219.0500',
   '2. high': '222.3600',
   '3. low': '170.2600',
   '4. close': '178.5800',
   '5. volume': '961321947'},
  '2018-10-31': {'1. open': '227.9500',
   '2. high': '233.4700',
   '3. low': '206.0900',
   '4. close': '218.8600',
   '5. volume': '789748068'},
  '2018-09-28': {'1. open': '228.4100',
   '2. high': '229.6700',
   '3. low': '215.3000',
   '4. close': '225.7400',
   '5. volume': '678972040'},
  '2018-08-31': {'1. open': '199.1300',
   '2. high': '228.8700',
   '3. low': '197.3100',
   '4. close': '227.6300',
   '5. volume': '700318837'},
  '2018-07-31': {'1. open': '183.8200',
   '2. high': '195.9600',
   '3. low': '183.4200',
   '4. close': '190.2900',
   '5. volume': '393843881'},
  '2018-06-29': {'1. open': '187.9900',
   '2. high': '194.2000',
   '3. low': '180.7300',
   '4. close': '185.1100',
   '5. volume': '527624365'},
  '2018-05-31': {'1. open': '166.4100',
   '2. high': '190.3700',
   '3. low': '165.2700',
   '4. close': '186.8700',
   '5. volume': '620976206'},
  '2018-04-30': {'1. open': '166.6400',
   '2. high': '178.9400',
   '3. low': '160.6300',
   '4. close': '165.2600',
   '5. volume': '666360147'},
  '2018-03-29': {'1. open': '178.5400',
   '2. high': '183.5000',
   '3. low': '164.9400',
   '4. close': '167.7800',
   '5. volume': '701387082'},
  '2018-02-28': {'1. open': '167.1700',
   '2. high': '180.6200',
   '3. low': '150.2400',
   '4. close': '178.1200',
   '5. volume': '888378184'},
  '2018-01-31': {'1. open': '170.1600',
   '2. high': '180.1000',
   '3. low': '164.7000',
   '4. close': '167.4300',
   '5. volume': '639245534'},
  '2017-12-29': {'1. open': '169.9500',
   '2. high': '177.2000',
   '3. low': '166.4600',
   '4. close': '169.2300',
   '5. volume': '518560008'},
  '2017-11-30': {'1. open': '169.8700',
   '2. high': '176.2400',
   '3. low': '165.2800',
   '4. close': '171.8500',
   '5. volume': '581374608'},
  '2017-10-31': {'1. open': '154.2600',
   '2. high': '169.6499',
   '3. low': '152.4600',
   '4. close': '169.0400',
   '5. volume': '496135305'},
  '2017-09-29': {'1. open': '164.8000',
   '2. high': '164.9400',
   '3. low': '149.1600',
   '4. close': '154.1200',
   '5. volume': '669594016'},
  '2017-08-31': {'1. open': '149.1000',
   '2. high': '164.5200',
   '3. low': '148.4100',
   '4. close': '164.0000',
   '5. volume': '638221161'},
  '2017-07-31': {'1. open': '144.8800',
   '2. high': '153.9900',
   '3. low': '142.4100',
   '4. close': '148.7300',
   '5. volume': '411377229'},
  '2017-06-30': {'1. open': '153.1700',
   '2. high': '155.9800',
   '3. low': '142.2000',
   '4. close': '144.0200',
   '5. volume': '664986406'},
  '2017-05-31': {'1. open': '145.1000',
   '2. high': '156.6500',
   '3. low': '144.2700',
   '4. close': '152.7600',
   '5. volume': '635292989'},
  '2017-04-28': {'1. open': '143.7100',
   '2. high': '145.4600',
   '3. low': '140.0600',
   '4. close': '143.6500',
   '5. volume': '371280180'},
  '2017-03-31': {'1. open': '137.8900',
   '2. high': '144.5000',
   '3. low': '137.0500',
   '4. close': '143.6600',
   '5. volume': '562091214'},
  '2017-02-28': {'1. open': '127.0300',
   '2. high': '137.4800',
   '3. low': '127.0100',
   '4. close': '136.9900',
   '5. volume': '574968547'},
  '2017-01-31': {'1. open': '115.8000',
   '2. high': '122.4400',
   '3. low': '114.7600',
   '4. close': '121.3500',
   '5. volume': '563331160'},
  '2016-12-30': {'1. open': '110.3650',
   '2. high': '118.0166',
   '3. low': '108.2500',
   '4. close': '115.8200',
   '5. volume': '608771645'},
  '2016-11-30': {'1. open': '113.4600',
   '2. high': '113.7700',
   '3. low': '104.0800',
   '4. close': '110.5200',
   '5. volume': '721554967'},
  '2016-10-31': {'1. open': '112.7100',
   '2. high': '118.6900',
   '3. low': '112.2800',
   '4. close': '113.5400',
   '5. volume': '686914224'},
  '2016-09-30': {'1. open': '106.1400',
   '2. high': '116.1800',
   '3. low': '102.5300',
   '4. close': '113.0500',
   '5. volume': '970096738'},
  '2016-08-31': {'1. open': '104.4100',
   '2. high': '110.2300',
   '3. low': '104.0000',
   '4. close': '106.1000',
   '5. volume': '630128567'},
  '2016-07-29': {'1. open': '95.4900',
   '2. high': '104.5500',
   '3. low': '94.3700',
   '4. close': '104.2100',
   '5. volume': '685779613'},
  '2016-06-30': {'1. open': '99.0200',
   '2. high': '101.8900',
   '3. low': '91.5000',
   '4. close': '95.6000',
   '5. volume': '780630235'},
  '2016-05-31': {'1. open': '93.9650',
   '2. high': '100.7300',
   '3. low': '89.4700',
   '4. close': '99.8600',
   '5. volume': '901144768'},
  '2016-04-29': {'1. open': '108.7800',
   '2. high': '112.3900',
   '3. low': '92.5100',
   '4. close': '93.7400',
   '5. volume': '872383623'},
  '2016-03-31': {'1. open': '97.6500',
   '2. high': '110.4200',
   '3. low': '97.4200',
   '4. close': '108.9900',
   '5. volume': '745756771'},
  '2016-02-29': {'1. open': '96.4700',
   '2. high': '98.8900',
   '3. low': '92.5900',
   '4. close': '96.6900',
   '5. volume': '810862547'},
  '2016-01-29': {'1. open': '102.6100',
   '2. high': '105.8500',
   '3. low': '92.3900',
   '4. close': '97.3400',
   '5. volume': '1271848087'},
  '2015-12-31': {'1. open': '118.7500',
   '2. high': '119.8600',
   '3. low': '104.8200',
   '4. close': '105.2600',
   '5. volume': '922626259'},
  '2015-11-30': {'1. open': '119.8700',
   '2. high': '123.8200',
   '3. low': '111.0000',
   '4. close': '118.3000',
   '5. volume': '750606735'},
  '2015-10-30': {'1. open': '109.0700',
   '2. high': '121.2200',
   '3. low': '107.3100',
   '4. close': '119.5000',
   '5. volume': '1113703829'},
  '2015-09-30': {'1. open': '110.1800',
   '2. high': '116.8900',
   '3. low': '107.3600',
   '4. close': '109.9500',
   '5. volume': '1203789074'},
  '2015-08-31': {'1. open': '121.5000',
   '2. high': '122.5700',
   '3. low': '92.0000',
   '4. close': '112.7600',
   '5. volume': '1606359115'},
  '2015-07-31': {'1. open': '126.9000',
   '2. high': '132.9700',
   '3. low': '119.2200',
   '4. close': '121.3000',
   '5. volume': '1058280697'},
  '2015-06-30': {'1. open': '131.2000',
   '2. high': '131.3900',
   '3. low': '124.4800',
   '4. close': '125.4250',
   '5. volume': '878606841'},
  '2015-05-29': {'1. open': '126.1000',
   '2. high': '132.9700',
   '3. low': '123.3600',
   '4. close': '130.2800',
   '5. volume': '954152126'},
  '2015-04-30': {'1. open': '124.8200',
   '2. high': '134.5400',
   '3. low': '123.1000',
   '4. close': '125.1500',
   '5. volume': '996135511'},
  '2015-03-31': {'1. open': '129.2500',
   '2. high': '130.2800',
   '3. low': '121.6300',
   '4. close': '124.4300',
   '5. volume': '1138641910'},
  '2015-02-27': {'1. open': '118.0500',
   '2. high': '133.6000',
   '3. low': '116.0800',
   '4. close': '128.4600',

In [5]:
def return_json(url):
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = url
    r = requests.get(url)
    data = r.json()
    return data

In [8]:
url = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol=AAPL&apikey={API_key}'

In [7]:
def convert_json_to_dataframe(data,dict_key):
    df = pd.DataFrame.from_dict(data[dict_key], orient='index')
    df = df.astype(float)
    df.columns = ['Open', 'High', 'Low', 'Close', 'Volume']
    df.index = pd.to_datetime(df.index)
    df = df.sort_index(ascending=False)
    return df

In [9]:
appl_income_statement = return_json(url)

In [10]:
appl_income_statement

{'symbol': 'AAPL',
 'annualReports': [{'fiscalDateEnding': '2025-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '195201000000',
   'totalRevenue': '416161000000',
   'costOfRevenue': '220960000000',
   'costofGoodsAndServicesSold': '220960000000',
   'operatingIncome': '133050000000',
   'sellingGeneralAndAdministrative': '8077000000',
   'researchAndDevelopment': '34550000000',
   'operatingExpenses': '62151000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': 'None',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '11698000000',
   'incomeBeforeTax': '132729000000',
   'incomeTaxExpense': '20719000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '112010000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '132729000000',
   'ebitda': '144427000000',
   'netIncome': '112010000000'},
  {'fiscalDateEnding': '2024-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '180683000000',
   'totalRevenue': '391035000000',
   'costOfRevenue': '210352000000',
   'costofGoodsAndServicesSold': '210352000000',
   'operatingIncome': '123216000000',
   'sellingGeneralAndAdministrative': '26097000000',
   'researchAndDevelopment': '31370000000',
   'operatingExpenses': '57467000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '0',
   'interestIncome': '0',
   'interestExpense': '0',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '11445000000',
   'incomeBeforeTax': '123485000000',
   'incomeTaxExpense': '29749000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '93736000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '123216000000',
   'ebitda': '134661000000',
   'netIncome': '93736000000'},
  {'fiscalDateEnding': '2023-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '169148000000',
   'totalRevenue': '383285000000',
   'costOfRevenue': '214137000000',
   'costofGoodsAndServicesSold': '214137000000',
   'operatingIncome': '114301000000',
   'sellingGeneralAndAdministrative': '24932000000',
   'researchAndDevelopment': '29915000000',
   'operatingExpenses': '54847000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-183000000',
   'interestIncome': '3750000000',
   'interestExpense': '3933000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '-382000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11519000000',
   'incomeBeforeTax': '113736000000',
   'incomeTaxExpense': '16741000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '96995000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '114301000000',
   'ebitda': '125820000000',
   'netIncome': '96995000000'},
  {'fiscalDateEnding': '2022-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '170782000000',
   'totalRevenue': '394328000000',
   'costOfRevenue': '223546000000',
   'costofGoodsAndServicesSold': '223546000000',
   'operatingIncome': '119437000000',
   'sellingGeneralAndAdministrative': '25094000000',
   'researchAndDevelopment': '26251000000',
   'operatingExpenses': '51573000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '-106000000',
   'interestIncome': '2825000000',
   'interestExpense': '2931000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '334000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11104000000',
   'incomeBeforeTax': '119103000000',
   'incomeTaxExpense': '19300000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '99803000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '119437000000',
   'ebitda': '130541000000',
   'netIncome': '99803000000'},
  {'fiscalDateEnding': '2021-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '152836000000',
   'totalRevenue': '365817000000',
   'costOfRevenue': '212981000000',
   'costofGoodsAndServicesSold': '212981000000',
   'operatingIncome': '108949000000',
   'sellingGeneralAndAdministrative': '21973000000',
   'researchAndDevelopment': '21914000000',
   'operatingExpenses': '43887000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '198000000',
   'interestIncome': '2843000000',
   'interestExpense': '2645000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '258000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11284000000',
   'incomeBeforeTax': '109207000000',
   'incomeTaxExpense': '14527000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '94680000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '111852000000',
   'ebitda': '123136000000',
   'netIncome': '94680000000'},
  {'fiscalDateEnding': '2020-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '104956000000',
   'totalRevenue': '274515000000',
   'costOfRevenue': '169559000000',
   'costofGoodsAndServicesSold': '169559000000',
   'operatingIncome': '66288000000',
   'sellingGeneralAndAdministrative': '19916000000',
   'researchAndDevelopment': '18752000000',
   'operatingExpenses': '38668000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '890000000',
   'interestIncome': '3763000000',
   'interestExpense': '2873000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '803000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11056000000',
   'incomeBeforeTax': '67091000000',
   'incomeTaxExpense': '9680000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '57411000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '69964000000',
   'ebitda': '81020000000',
   'netIncome': '57411000000'},
  {'fiscalDateEnding': '2019-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '98392000000',
   'totalRevenue': '260174000000',
   'costOfRevenue': '161782000000',
   'costofGoodsAndServicesSold': '161782000000',
   'operatingIncome': '63930000000',
   'sellingGeneralAndAdministrative': '18245000000',
   'researchAndDevelopment': '16217000000',
   'operatingExpenses': '34462000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '1385000000',
   'interestIncome': '4961000000',
   'interestExpense': '3576000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '1807000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '12547000000',
   'incomeBeforeTax': '65737000000',
   'incomeTaxExpense': '10481000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '55256000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '69313000000',
   'ebitda': '81860000000',
   'netIncome': '55256000000'},
  {'fiscalDateEnding': '2018-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '101839000000',
   'totalRevenue': '265595000000',
   'costOfRevenue': '163756000000',
   'costofGoodsAndServicesSold': '163756000000',
   'operatingIncome': '70898000000',
   'sellingGeneralAndAdministrative': '16705000000',
   'researchAndDevelopment': '14236000000',
   'operatingExpenses': '30941000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '2446000000',
   'interestIncome': '5686000000',
   'interestExpense': '3240000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '2005000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '10903000000',
   'incomeBeforeTax': '72903000000',
   'incomeTaxExpense': '13372000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '59531000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '76143000000',
   'ebitda': '87046000000',
   'netIncome': '59531000000'},
  {'fiscalDateEnding': '2017-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '88186000000',
   'totalRevenue': '229234000000',
   'costOfRevenue': '141048000000',
   'costofGoodsAndServicesSold': '141048000000',
   'operatingIncome': '61344000000',
   'sellingGeneralAndAdministrative': '15261000000',
   'researchAndDevelopment': '11581000000',
   'operatingExpenses': '26842000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '2878000000',
   'interestIncome': '5201000000',
   'interestExpense': '2323000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '2745000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '10157000000',
   'incomeBeforeTax': '64089000000',
   'incomeTaxExpense': '15738000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '48351000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '66412000000',
   'ebitda': '76569000000',
   'netIncome': '48351000000'},
  {'fiscalDateEnding': '2016-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '84263000000',
   'totalRevenue': '215639000000',
   'costOfRevenue': '131376000000',
   'costofGoodsAndServicesSold': '131376000000',
   'operatingIncome': '60024000000',
   'sellingGeneralAndAdministrative': '14194000000',
   'researchAndDevelopment': '10045000000',
   'operatingExpenses': '24239000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': '2543000000',
   'interestIncome': '3999000000',
   'interestExpense': '1456000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '1348000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '10505000000',
   'incomeBeforeTax': '61372000000',
   'incomeTaxExpense': '15685000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '45687000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '62828000000',
   'ebitda': '73333000000',
   'netIncome': '45687000000'},
  {'fiscalDateEnding': '2015-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '93626000000',
   'totalRevenue': '233715000000',
   'costOfRevenue': '140089000000',
   'costofGoodsAndServicesSold': '140089000000',
   'operatingIncome': '71230000000',
   'sellingGeneralAndAdministrative': '14329000000',
   'researchAndDevelopment': '8067000000',
   'operatingExpenses': '22396000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '733000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '1285000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '11257000000',
   'incomeBeforeTax': '72515000000',
   'incomeTaxExpense': '19121000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '53394000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '73248000000',
   'ebitda': '84505000000',
   'netIncome': '53394000000'},
  {'fiscalDateEnding': '2014-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '70537000000',
   'totalRevenue': '182795000000',
   'costOfRevenue': '112258000000',
   'costofGoodsAndServicesSold': '112258000000',
   'operatingIncome': '52503000000',
   'sellingGeneralAndAdministrative': '11993000000',
   'researchAndDevelopment': '6041000000',
   'operatingExpenses': '18034000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '384000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '980000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '7946000000',
   'incomeBeforeTax': '53483000000',
   'incomeTaxExpense': '13973000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '39510000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '53867000000',
   'ebitda': '61813000000',
   'netIncome': '39510000000'},
  {'fiscalDateEnding': '2013-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '64304000000',
   'totalRevenue': '170910000000',
   'costOfRevenue': '106606000000',
   'costofGoodsAndServicesSold': '106606000000',
   'operatingIncome': '48999000000',
   'sellingGeneralAndAdministrative': '9730000000',
   'researchAndDevelopment': '4475000000',
   'operatingExpenses': '15305000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '136000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '1156000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '6757000000',
   'incomeBeforeTax': '50155000000',
   'incomeTaxExpense': '13118000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '37037000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '50291000000',
   'ebitda': '57048000000',
   'netIncome': '37037000000'},
  {'fiscalDateEnding': '2012-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '68662000000',
   'totalRevenue': '156508000000',
   'costOfRevenue': '87846000000',
   'costofGoodsAndServicesSold': '87846000000',
   'operatingIncome': '55241000000',
   'sellingGeneralAndAdministrative': '9040000000',
   'researchAndDevelopment': '3381000000',
   'operatingExpenses': '13421000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '522000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '522000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '3277000000',
   'incomeBeforeTax': '55763000000',
   'incomeTaxExpense': '14030000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '41733000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '55763000000',
   'ebitda': '59040000000',
   'netIncome': '41733000000'},
  {'fiscalDateEnding': '2011-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '43818000000',
   'totalRevenue': '108249000000',
   'costOfRevenue': '64431000000',
   'costofGoodsAndServicesSold': '64431000000',
   'operatingIncome': '33790000000',
   'sellingGeneralAndAdministrative': '7599000000',
   'researchAndDevelopment': '2429000000',
   'operatingExpenses': '10028000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '415000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '415000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '1814000000',
   'incomeBeforeTax': '34205000000',
   'incomeTaxExpense': '8283000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '25922000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '34205000000',
   'ebitda': '36019000000',
   'netIncome': '25922000000'},
  {'fiscalDateEnding': '2010-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '25684000000',
   'totalRevenue': '65225000000',
   'costOfRevenue': '39541000000',
   'costofGoodsAndServicesSold': '39541000000',
   'operatingIncome': '18385000000',
   'sellingGeneralAndAdministrative': '5517000000',
   'researchAndDevelopment': '1782000000',
   'operatingExpenses': '7299000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '155000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '155000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '1027000000',
   'incomeBeforeTax': '18540000000',
   'incomeTaxExpense': '4527000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '14013000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '18385000000',
   'ebitda': '19412000000',
   'netIncome': '14013000000'},
  {'fiscalDateEnding': '2009-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '17222000000',
   'totalRevenue': '42905000000',
   'costOfRevenue': '25683000000',
   'costofGoodsAndServicesSold': '25683000000',
   'operatingIncome': '11740000000',
   'sellingGeneralAndAdministrative': '4149000000',
   'researchAndDevelopment': '1333000000',
   'operatingExpenses': '5482000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '326000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': '326000000',
   'depreciation': 'None',
   'depreciationAndAmortization': '734000000',
   'incomeBeforeTax': '12066000000',
   'incomeTaxExpense': '3831000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': '8235000000',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '11740000000',
   'ebitda': '12474000000',
   'netIncome': '8235000000'},
  {'fiscalDateEnding': '2008-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '11145000000',
   'totalRevenue': '32479000000',
   'costOfRevenue': '21334000000',
   'costofGoodsAndServicesSold': '21334000000',
   'operatingIncome': '6275000000',
   'sellingGeneralAndAdministrative': '3761000000',
   'researchAndDevelopment': '1109000000',
   'operatingExpenses': '4870000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '620000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '409000000',
   'incomeBeforeTax': '6895000000',
   'incomeTaxExpense': '2061000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '6895000000',
   'ebitda': '7304000000',
   'netIncome': '4834000000'},
  {'fiscalDateEnding': '2007-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '8154000000',
   'totalRevenue': '24006000000',
   'costOfRevenue': '15852000000',
   'costofGoodsAndServicesSold': '15852000000',
   'operatingIncome': '4409000000',
   'sellingGeneralAndAdministrative': '2963000000',
   'researchAndDevelopment': '782000000',
   'operatingExpenses': '3745000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '599000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '317000000',
   'incomeBeforeTax': '5008000000',
   'incomeTaxExpense': '1512000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '4407000000',
   'ebitda': '4724000000',
   'netIncome': '3495000000'},
  {'fiscalDateEnding': '2006-09-30',
   'reportedCurrency': 'USD',
   'grossProfit': '5598000000',
   'totalRevenue': '19315000000',
   'costOfRevenue': '13717000000',
   'costofGoodsAndServicesSold': '13717000000',
   'operatingIncome': '2453000000',
   'sellingGeneralAndAdministrative': '2433000000',
   'researchAndDevelopment': '712000000',
   'operatingExpenses': '3145000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': '365000000',
   'nonInterestIncome': 'None',
   'otherNonOperatingIncome': 'None',
   'depreciation': 'None',
   'depreciationAndAmortization': '225000000',
   'incomeBeforeTax': '2818000000',
   'incomeTaxExpense': '829000000',
   'interestAndDebtExpense': 'None',
   'netIncomeFromContinuingOperations': 'None',
   'comprehensiveIncomeNetOfTax': 'None',
   'ebit': '2453000000',
   'ebitda': '2678000000',
   'netIncome': '1989000000'}],
 'quarterlyReports': [{'fiscalDateEnding': '2025-12-31',
   'reportedCurrency': 'USD',
   'grossProfit': '69231000000',
   'totalRevenue': '143756000000',
   'costOfRevenue': '74525000000',
   'costofGoodsAndServicesSold': '74525000000',
   'operatingIncome': '50852000000',
   'sellingGeneralAndAdministrative': '2095000000',
   'researchAndDevelopment': '10887000000',
   'operatingExpenses': '18379000000',
   'investmentIncomeNet': 'None',
   'netInterestIncome': 'None',
   'interestIncome': 'None',
   'interestExpense': 'None',
   'nonInterestIncome': 'None',

In [38]:
df_income = pd.json_normalize(appl_income_statement.get("annualReports"))

In [76]:
df_income.set_index("fiscalDateEnding",inplace=True)

In [77]:
df_income

,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,investmentIncomeNet,netInterestIncome,interestIncome,interestExpense,nonInterestIncome,otherNonOperatingIncome,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
fiscalDateEnding,,,,,,,,,,,,,,,,,,,,,,,,,
2025-09-30,USD,195201000000,416161000000,220960000000,220960000000,133050000000,8077000000,34550000000,62151000000,None,None,None,None,None,None,None,11698000000,132729000000,20719000000,None,112010000000,None,132729000000,144427000000,112010000000
2024-09-30,USD,180683000000,391035000000,210352000000,210352000000,123216000000,26097000000,31370000000,57467000000,None,0,0,0,None,None,None,11445000000,123485000000,29749000000,None,93736000000,None,123216000000,134661000000,93736000000
2023-09-30,USD,169148000000,383285000000,214137000000,214137000000,114301000000,24932000000,29915000000,54847000000,None,-183000000,3750000000,3933000000,None,-382000000,None,11519000000,113736000000,16741000000,None,96995000000,None,114301000000,125820000000,96995000000
2022-09-30,USD,170782000000,394328000000,223546000000,223546000000,119437000000,25094000000,26251000000,51573000000,None,-106000000,2825000000,2931000000,None,334000000,None,11104000000,119103000000,19300000000,None,99803000000,None,119437000000,130541000000,99803000000
2021-09-30,USD,152836000000,365817000000,212981000000,212981000000,108949000000,21973000000,21914000000,43887000000,None,198000000,2843000000,2645000000,None,258000000,None,11284000000,109207000000,14527000000,None,94680000000,None,111852000000,123136000000,94680000000
2020-09-30,USD,104956000000,274515000000,169559000000,169559000000,66288000000,19916000000,18752000000,38668000000,None,890000000,3763000000,2873000000,None,803000000,None,11056000000,67091000000,9680000000,None,57411000000,None,69964000000,81020000000,57411000000
2019-09-30,USD,98392000000,260174000000,161782000000,161782000000,63930000000,18245000000,16217000000,34462000000,None,1385000000,4961000000,3576000000,None,1807000000,None,12547000000,65737000000,10481000000,None,55256000000,None,69313000000,81860000000,55256000000
2018-09-30,USD,101839000000,265595000000,163756000000,163756000000,70898000000,16705000000,14236000000,30941000000,None,2446000000,5686000000,3240000000,None,2005000000,None,10903000000,72903000000,13372000000,None,59531000000,None,76143000000,87046000000,59531000000
2017-09-30,USD,88186000000,229234000000,141048000000,141048000000,61344000000,15261000000,11581000000,26842000000,None,2878000000,5201000000,2323000000,None,2745000000,None,10157000000,64089000000,15738000000,None,48351000000,None,66412000000,76569000000,48351000000
2016-09-30,USD,84263000000,215639000000,131376000000,131376000000,60024000000,14194000000,10045000000,24239000000,None,2543000000,3999000000,1456000000,None,1348000000,None,10505000000,61372000000,15685000000,None,45687000000,None,62828000000,73333000000,45687000000
2015-09-30,USD,93626000000,233715000000,140089000000,140089000000,71230000000,14329000000,8067000000,22396000000,None,None,None,733000000,None,1285000000,None,11257000000,72515000000,19121000000,None,53394000000,None,73248000000,84505000000,53394000000
2014-09-30,USD,70537000000,182795000000,112258000000,112258000000,52503000000,11993000000,6041000000,18034000000,None,None,None,384000000,None,980000000,None,7946000000,53483000000,13973000000,None,39510000000,None,53867000000,61813000000,39510000000
2013-09-30,USD,64304000000,170910000000,106606000000,106606000000,48999000000,9730000000,4475000000,15305000000,None,None,None,136000000,None,1156000000,None,6757000000,50155000000,13118000000,None,37037000000,None,50291000000,57048000000,37037000000
2012-09-30,USD,68662000000,156508000000,87846000000,87846000000,55241000000,9040000000,3381000000,13421000000,None,None,None,522000000,None,522000000,None,3277000000,55763000000,14030000000,None,41733000000,None,55763000000,59040000000,41733000000
2011-09-30,USD,43818000000,108249000000,64431000000,64431000000,33790000000,7599000000,2429000000,10028000000,None,None,None,415000000,None,415000000,None,1814000000,34205000000,8283000000,None,25922000000,None,34205000000,36019000000,25922000000
2010-09-30,USD,25684000000,65225000000,39541000000,39541000000,18385000000,5517000000,1782000000,7299000000,None,None,None,155000000,None,155000000,None,1027000000,18540000000,4527000000,None,14013000000,None,18385000000,19412000000,14013000000
2009-09-30,USD,17222000000,42905000000,25683000000,25683000000,11740000000,4149000000,1333000000,5482000000,None,None,None,326000000,None,326000000,None,734000000,12066000000,3831000000,None,8235000000,None,11740000000,12474000000,8235000000
2008-09-30,USD,11145000000,32479000000,21334000000,21334000000,6275000000,3761000000,1109000000,4870000000,None,None,None,620000000,None,None,None,409000000,6895000000,2061000000,None,None,None,6895000000,7304000000,4834000000
2007-09-30,USD,8154000000,24006000000,15852000000,15852000000,4409000000,2963000000,782000000,3745000000,None,None,None,599000000,None,None,None,317000000,5008000000,1512000000,None,None,None,4407000000,4724000000,3495000000
2006-09-30,USD,5598000000,19315000000,13717000000,13717000000,2453000000,2433000000,712000000,3145000000,None,None,None,365000000,None,None,None,225000000,2818000000,829000000,None,None,None,2453000000,2678000000,1989000000

In [11]:
url = f'https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol=AAPL&apikey={API_key}'
appl_balance_sheet = return_json(url)

In [43]:
df_balance_sheet = pd.json_normalize(appl_balance_sheet.get("annualReports")).set_index("fiscalDateEnding")

In [44]:
df_balance_sheet

,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
fiscalDateEnding,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-09-30,USD,359241000000,147957000000,35934000000,35934000000,5718000000,72957000000,211284000000,61039000000,None,None,None,None,None,77723000000,18763000000,14585000000,None,285508000000,165631000000,69860000000,None,None,22446000000,119877000000,None,78328000000,20329000000,None,112377000000,64270000000,41549000000,73733000000,None,-14264000000,93568000000,15004697000
2024-09-30,USD,364980000000,152987000000,29943000000,29943000000,7286000000,66243000000,211993000000,55914000000,None,None,None,None,None,91479000000,35228000000,14287000000,None,308030000000,176392000000,68960000000,None,None,22511000000,131638000000,None,85750000000,20879000000,None,119059000000,50071000000,36634000000,56950000000,None,-19154000000,83276000000,15408095000
2023-09-30,USD,352583000000,143566000000,29965000000,29965000000,6331000000,29508000000,209017000000,43715000000,None,None,None,None,None,100544000000,31590000000,14695000000,None,290437000000,145308000000,62611000000,None,None,15807000000,145129000000,12842000000,95281000000,15807000000,None,111947000000,58829000000,49848000000,62146000000,None,-214000000,73812000000,15812547000
2022-09-30,USD,352755000000,135405000000,23646000000,23646000000,4946000000,28184000000,217350000000,42117000000,72340000000,None,None,None,None,120805000000,24658000000,21223000000,None,302083000000,153982000000,64115000000,None,None,21110000000,148101000000,12411000000,98959000000,21110000000,None,120881000000,60845000000,49142000000,50672000000,None,-3068000000,64849000000,16325819000
2021-09-30,USD,351002000000,134836000000,34940000000,34940000000,6580000000,26278000000,216166000000,39440000000,70283000000,None,None,None,None,127877000000,27699000000,14111000000,None,287912000000,125481000000,54763000000,None,None,15613000000,162431000000,11803000000,109106000000,15613000000,None,124719000000,47493000000,28636000000,63090000000,None,5562000000,57365000000,16864919000
2020-09-30,USD,323888000000,143713000000,38016000000,38016000000,4061000000,16120000000,180175000000,36766000000,66760000000,None,None,None,None,100887000000,52927000000,11264000000,None,258549000000,105392000000,42296000000,None,None,13769000000,153157000000,9842000000,98667000000,13769000000,None,112436000000,42684000000,26320000000,65339000000,None,14966000000,50779000000,17528214000
2019-09-30,USD,338516000000,162819000000,48844000000,48844000000,4106000000,22926000000,175697000000,37378000000,58579000000,None,None,None,None,105341000000,51713000000,12352000000,None,248028000000,105718000000,46236000000,None,None,16240000000,142310000000,None,91807000000,16240000000,None,108047000000,37720000000,20958000000,90488000000,None,45898000000,45174000000,18595652000
2018-09-30,USD,365725000000,131339000000,25913000000,25913000000,3956000000,23186000000,234386000000,41304000000,49099000000,None,None,None,None,170799000000,40388000000,12087000000,None,258578000000,116866000000,55888000000,None,None,20748000000,141712000000,None,93735000000,20748000000,None,114483000000,32687000000,11165000000,107147000000,None,70400000000,40201000000,20000436000
2017-09-30,USD,375319000000,128645000000,20289000000,20289000000,4855000000,35673000000,246674000000,33783000000,41293000000,2298000000,2298000000,5717000000,None,194714000000,53892000000,13936000000,None,241272000000,100814000000,44242000000,None,None,18473000000,140458000000,None,97207000000,18473000000,None,115680000000,25744000000,40415000000,134047000000,0,98330000000,35867000000,21006768000
2016-09-30,USD,321686000000,106869000000,20484000000,20484000000,2132000000,29299000000,214817000000,27010000000,34235000000,3206000000,3206000000,5414000000,None,170430000000,46671000000,8283000000,None,193437000000,79006000000,37294000000,None,None,11605000000,114431000000,None,75427000000,11605000000,None,87032000000,22027000000,36074000000,128249000000,None,96364000000,31251000000,22001124000
2015-09-30,USD,290479000000,89378000000,21120000000,21120000000,2349000000,30343000000,201101000000,22471000000,26786000000,3893000000,3893000000,5116000000,None,164065000000,20481000000,9539000000,None,171124000000,80610000000,35490000000,None,None,10999000000,90514000000,None,53463000000,2513000000,None,64462000000,25181000000,33427000000,119355000000,0,92284000000,27416000000,23172276000
2014-09-30,USD,231839000000,68531000000,13844000000,13844000000,2111000000,4232000000,163308000000,20624000000,18391000000,4142000000,4142000000,4616000000,None,130162000000,11233000000,9806000000,None,120292000000,63448000000,30196000000,None,None,6308000000,56844000000,None,28987000000,35295000000,None,35295000000,18453000000,24826000000,111547000000,0,87152000000,23313000000,24490652000
2013-09-30,USD,207000000000,73286000000,14259000000,14259000000,1764000000,2172000000,133714000000,16597000000,11922000000,4179000000,4179000000,1577000000,None,106215000000,26287000000,6882000000,None,83451000000,43658000000,22367000000,None,None,7679000000,39793000000,None,16960000000,None,None,16960000000,13856000000,20208000000,123549000000,0,104256000000,19764000000,26086536000
2012-09-30,USD,176064000000,57653000000,10746000000,10746000000,791000000,5551000000,118411000000,15452000000,6435000000,4224000000,4224000000,1135000000,None,92122000000,18383000000,6458000000,None,57854000000,38542000000,21175000000,None,None,6310000000,19312000000,None,None,None,None,None,11414000000,16664000000,118210000000,0,101289000000,16422000000,26469940000
2011-09-30,USD,116371000000,44988000000,9815000000,9815000000,776000000,5369000000,71383000000,7777000000,3991000000,3536000000,3536000000,896000000,None,55618000000,16137000000,4529000000,None,39756000000,27970000000,14632000000,None,None,5606000000,11786000000,None,None,None,None,None,9247000000,10100000000,76615000000,0,62841000000,13331000000,26226060000
2010-09-30,USD,75183000000,41678000000,11261000000,11261000000,1051000000,5510000000,33505000000,4768000000,2466000000,342000000,342000000,741000000,None,25391000000,14359000000,3447000000,None,27392000000,20722000000,12015000000,None,None,2466000000,6670000000,None,None,None,None,None,5723000000,5531000000,47791000000,0,37169000000,10668000000,25891936000
2009-09-30,USD,53851000000,36265000000,5263000000,5263000000,455000000,3361000000,17586000000,2954000000,1713000000,247000000,247000000,206000000,None,10528000000,18201000000,6884000000,None,26019000000,19282000000,5601000000,None,None,1948000000,6737000000,None,None,None,None,None,3376000000,3502000000,27832000000,0,19538000000,8210000000,25396140000
2008-09-30,USD,39572000000,34690000000,11875000000,11875000000,509000000,2422000000,4882000000,2455000000,1292000000,285000000,285000000,207000000,None,None,12615000000,5822000000,None,18542000000,14092000000,5520000000,None,None,2507000000,4450000000,None,None,None,None,None,3719000000,None,21030000000,None,13845000000,7177000000,25259892000
2007-09-30,USD,25347000000,21956000000,9352000000,9352000000,346000000,4029000000,3391000000,1832000000,1009000000,299000000,299000000,38000000,None,None,6034000000,996000000,None,10815000000,9299000000,4970000000,None,None,1805000000,1516000000,None,None,None,None,None,2919000000,None,14532000000,None,9101000000,5368000000,24900176000
2006-09-30,USD,17205000000,14509000000,6392000000,6392000000,270000000,2845000000,2696000000,1281000000,794000000,139000000,139000000,38000000,None,None,3718000000,469000000,None,7221000000,6471000000,3390000000,None,None,1515000000,750000000,None,None,None,None,None,2335000000,None,9984000000,None,5607000000,4355000000,24570728000

In [12]:
url = f'https://www.alphavantage.co/query?function=CASH_FLOW&symbol=AAPL&apikey={API_key}'
appl_cashflow_statement = return_json(url)

In [14]:
appl_cashflow_statement

{'symbol': 'AAPL',
 'annualReports': [{'fiscalDateEnding': '2025-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '111482000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11698000000',
   'capitalExpenditures': '12715000000',
   'changeInReceivables': 'None',
   'changeInInventory': '1400000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '15195000000',
   'cashflowFromFinancing': '-120686000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '15421000000',
   'dividendPayoutCommonStock': '15421000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-90711000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '12863000000',
   'changeInCashAndCashEquivalents': 'None',
   'changeInExchangeRate': 'None',
   'netIncome': '112010000000'},
  {'fiscalDateEnding': '2024-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '118254000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11445000000',
   'capitalExpenditures': '9447000000',
   'changeInReceivables': 'None',
   'changeInInventory': '-1046000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '2935000000',
   'cashflowFromFinancing': '-121983000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '15234000000',
   'dividendPayoutCommonStock': '15234000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-94949000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '11688000000',
   'changeInCashAndCashEquivalents': 'None',
   'changeInExchangeRate': 'None',
   'netIncome': '93736000000'},
  {'fiscalDateEnding': '2023-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '110543000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11519000000',
   'capitalExpenditures': '10959000000',
   'changeInReceivables': '-417000000',
   'changeInInventory': '-1618000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '3705000000',
   'cashflowFromFinancing': '-108488000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '15025000000',
   'dividendPayoutCommonStock': '15025000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-77550000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '10833000000',
   'changeInCashAndCashEquivalents': '5760000000',
   'changeInExchangeRate': 'None',
   'netIncome': '96995000000'},
  {'fiscalDateEnding': '2022-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '122151000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11104000000',
   'capitalExpenditures': '10708000000',
   'changeInReceivables': '-9343000000',
   'changeInInventory': '1484000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-22354000000',
   'cashflowFromFinancing': '-110749000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '14841000000',
   'dividendPayoutCommonStock': '14841000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-89402000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '9038000000',
   'changeInCashAndCashEquivalents': '-10952000000',
   'changeInExchangeRate': 'None',
   'netIncome': '99803000000'},
  {'fiscalDateEnding': '2021-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '104038000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11284000000',
   'capitalExpenditures': '11085000000',
   'changeInReceivables': '-14028000000',
   'changeInInventory': '-2642000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-14545000000',
   'cashflowFromFinancing': '-93353000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '14467000000',
   'dividendPayoutCommonStock': '14467000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-85971000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '7906000000',
   'changeInCashAndCashEquivalents': '-3860000000',
   'changeInExchangeRate': 'None',
   'netIncome': '94680000000'},
  {'fiscalDateEnding': '2020-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '80674000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11056000000',
   'capitalExpenditures': '7309000000',
   'changeInReceivables': '8470000000',
   'changeInInventory': '-127000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-4289000000',
   'cashflowFromFinancing': '-86820000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '14081000000',
   'dividendPayoutCommonStock': '14081000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-72358000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '6829000000',
   'changeInCashAndCashEquivalents': '-10435000000',
   'changeInExchangeRate': 'None',
   'netIncome': '57411000000'},
  {'fiscalDateEnding': '2019-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '69391000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '12547000000',
   'capitalExpenditures': '10495000000',
   'changeInReceivables': '3176000000',
   'changeInInventory': '-289000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '45896000000',
   'cashflowFromFinancing': '-90976000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '14119000000',
   'dividendPayoutCommonStock': '14119000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-66897000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '6068000000',
   'changeInCashAndCashEquivalents': '24311000000',
   'changeInExchangeRate': 'None',
   'netIncome': '55256000000'},
  {'fiscalDateEnding': '2018-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '77434000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '10903000000',
   'capitalExpenditures': '13313000000',
   'changeInReceivables': '-13332000000',
   'changeInInventory': '828000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '16066000000',
   'cashflowFromFinancing': '-87876000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '13712000000',
   'dividendPayoutCommonStock': '13712000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-72738000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '5340000000',
   'changeInCashAndCashEquivalents': '5624000000',
   'changeInExchangeRate': 'None',
   'netIncome': '59531000000'},
  {'fiscalDateEnding': '2017-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '63598000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '10157000000',
   'capitalExpenditures': '12451000000',
   'changeInReceivables': '-6347000000',
   'changeInInventory': '-2723000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-46446000000',
   'cashflowFromFinancing': '-17347000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '12769000000',
   'dividendPayoutCommonStock': '12769000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-32345000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '4840000000',
   'changeInCashAndCashEquivalents': '-195000000',
   'changeInExchangeRate': 'None',
   'netIncome': '48351000000'},
  {'fiscalDateEnding': '2016-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '65824000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '10505000000',
   'capitalExpenditures': '12734000000',
   'changeInReceivables': '1044000000',
   'changeInInventory': '217000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-45977000000',
   'cashflowFromFinancing': '-20483000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '12150000000',
   'dividendPayoutCommonStock': '12150000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-29722000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '4210000000',
   'changeInCashAndCashEquivalents': '-636000000',
   'changeInExchangeRate': 'None',
   'netIncome': '45687000000'},
  {'fiscalDateEnding': '2015-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '81266000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '11257000000',
   'capitalExpenditures': '11247000000',
   'changeInReceivables': '611000000',
   'changeInInventory': '-238000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-56274000000',
   'cashflowFromFinancing': '-17716000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '11561000000',
   'dividendPayoutCommonStock': '11561000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-35253000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '3586000000',
   'changeInCashAndCashEquivalents': '7276000000',
   'changeInExchangeRate': 'None',
   'netIncome': '53394000000'},
  {'fiscalDateEnding': '2014-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '59713000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '7946000000',
   'capitalExpenditures': '9571000000',
   'changeInReceivables': '-6452000000',
   'changeInInventory': '-76000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-22579000000',
   'cashflowFromFinancing': '-37549000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '11126000000',
   'dividendPayoutCommonStock': '11126000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-45000000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '2863000000',
   'changeInCashAndCashEquivalents': '-415000000',
   'changeInExchangeRate': 'None',
   'netIncome': '39510000000'},
  {'fiscalDateEnding': '2013-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '53666000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '6757000000',
   'capitalExpenditures': '8165000000',
   'changeInReceivables': '-1949000000',
   'changeInInventory': '-973000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-33774000000',
   'cashflowFromFinancing': '-16379000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '10564000000',
   'dividendPayoutCommonStock': '10564000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '-22860000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '2253000000',
   'changeInCashAndCashEquivalents': '3513000000',
   'changeInExchangeRate': 'None',
   'netIncome': '37037000000'},
  {'fiscalDateEnding': '2012-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '50856000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '3277000000',
   'capitalExpenditures': '8295000000',
   'changeInReceivables': '-6965000000',
   'changeInInventory': '-15000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-48227000000',
   'cashflowFromFinancing': '-1698000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': '2488000000',
   'dividendPayoutCommonStock': '2488000000',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '665000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '1740000000',
   'changeInCashAndCashEquivalents': '931000000',
   'changeInExchangeRate': 'None',
   'netIncome': '41733000000'},
  {'fiscalDateEnding': '2011-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '37529000000',
   'paymentsForOperatingActivities': 'None',
   'proceedsFromOperatingActivities': 'None',
   'changeInOperatingLiabilities': 'None',
   'changeInOperatingAssets': 'None',
   'depreciationDepletionAndAmortization': '1814000000',
   'capitalExpenditures': '4260000000',
   'changeInReceivables': '-1791000000',
   'changeInInventory': '275000000',
   'profitLoss': 'None',
   'cashflowFromInvestment': '-40419000000',
   'cashflowFromFinancing': '1444000000',
   'proceedsFromRepaymentsOfShortTermDebt': 'None',
   'paymentsForRepurchaseOfCommonStock': 'None',
   'paymentsForRepurchaseOfEquity': 'None',
   'paymentsForRepurchaseOfPreferredStock': 'None',
   'dividendPayout': 'None',
   'dividendPayoutCommonStock': 'None',
   'dividendPayoutPreferredStock': 'None',
   'proceedsFromIssuanceOfCommonStock': 'None',
   'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet': 'None',
   'proceedsFromIssuanceOfPreferredStock': 'None',
   'proceedsFromRepurchaseOfEquity': '831000000',
   'proceedsFromSaleOfTreasuryStock': 'None',
   'stockBasedCompensation': '1168000000',
   'changeInCashAndCashEquivalents': '-1446000000',
   'changeInExchangeRate': 'None',
   'netIncome': '25922000000'},
  {'fiscalDateEnding': '2010-09-30',
   'reportedCurrency': 'USD',
   'operatingCashflow': '18595000000',
   'paymentsForOperatingActivities': 'None',

In [45]:
df_cashflow = pd.json_normalize(appl_cashflow_statement.get("annualReports")).set_index("fiscalDateEnding")

In [46]:
df_cashflow

,reportedCurrency,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,changeInInventory,profitLoss,cashflowFromInvestment,cashflowFromFinancing,proceedsFromRepaymentsOfShortTermDebt,paymentsForRepurchaseOfCommonStock,paymentsForRepurchaseOfEquity,paymentsForRepurchaseOfPreferredStock,dividendPayout,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,stockBasedCompensation,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome
fiscalDateEnding,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2025-09-30,USD,111482000000,None,None,None,None,11698000000,12715000000,None,1400000000,None,15195000000,-120686000000,None,None,None,None,15421000000,15421000000,None,None,None,None,-90711000000,None,12863000000,None,None,112010000000
2024-09-30,USD,118254000000,None,None,None,None,11445000000,9447000000,None,-1046000000,None,2935000000,-121983000000,None,None,None,None,15234000000,15234000000,None,None,None,None,-94949000000,None,11688000000,None,None,93736000000
2023-09-30,USD,110543000000,None,None,None,None,11519000000,10959000000,-417000000,-1618000000,None,3705000000,-108488000000,None,None,None,None,15025000000,15025000000,None,None,None,None,-77550000000,None,10833000000,5760000000,None,96995000000
2022-09-30,USD,122151000000,None,None,None,None,11104000000,10708000000,-9343000000,1484000000,None,-22354000000,-110749000000,None,None,None,None,14841000000,14841000000,None,None,None,None,-89402000000,None,9038000000,-10952000000,None,99803000000
2021-09-30,USD,104038000000,None,None,None,None,11284000000,11085000000,-14028000000,-2642000000,None,-14545000000,-93353000000,None,None,None,None,14467000000,14467000000,None,None,None,None,-85971000000,None,7906000000,-3860000000,None,94680000000
2020-09-30,USD,80674000000,None,None,None,None,11056000000,7309000000,8470000000,-127000000,None,-4289000000,-86820000000,None,None,None,None,14081000000,14081000000,None,None,None,None,-72358000000,None,6829000000,-10435000000,None,57411000000
2019-09-30,USD,69391000000,None,None,None,None,12547000000,10495000000,3176000000,-289000000,None,45896000000,-90976000000,None,None,None,None,14119000000,14119000000,None,None,None,None,-66897000000,None,6068000000,24311000000,None,55256000000
2018-09-30,USD,77434000000,None,None,None,None,10903000000,13313000000,-13332000000,828000000,None,16066000000,-87876000000,None,None,None,None,13712000000,13712000000,None,None,None,None,-72738000000,None,5340000000,5624000000,None,59531000000
2017-09-30,USD,63598000000,None,None,None,None,10157000000,12451000000,-6347000000,-2723000000,None,-46446000000,-17347000000,None,None,None,None,12769000000,12769000000,None,None,None,None,-32345000000,None,4840000000,-195000000,None,48351000000
2016-09-30,USD,65824000000,None,None,None,None,10505000000,12734000000,1044000000,217000000,None,-45977000000,-20483000000,None,None,None,None,12150000000,12150000000,None,None,None,None,-29722000000,None,4210000000,-636000000,None,45687000000
2015-09-30,USD,81266000000,None,None,None,None,11257000000,11247000000,611000000,-238000000,None,-56274000000,-17716000000,None,None,None,None,11561000000,11561000000,None,None,None,None,-35253000000,None,3586000000,7276000000,None,53394000000
2014-09-30,USD,59713000000,None,None,None,None,7946000000,9571000000,-6452000000,-76000000,None,-22579000000,-37549000000,None,None,None,None,11126000000,11126000000,None,None,None,None,-45000000000,None,2863000000,-415000000,None,39510000000
2013-09-30,USD,53666000000,None,None,None,None,6757000000,8165000000,-1949000000,-973000000,None,-33774000000,-16379000000,None,None,None,None,10564000000,10564000000,None,None,None,None,-22860000000,None,2253000000,3513000000,None,37037000000
2012-09-30,USD,50856000000,None,None,None,None,3277000000,8295000000,-6965000000,-15000000,None,-48227000000,-1698000000,None,None,None,None,2488000000,2488000000,None,None,None,None,665000000,None,1740000000,931000000,None,41733000000
2011-09-30,USD,37529000000,None,None,None,None,1814000000,4260000000,-1791000000,275000000,None,-40419000000,1444000000,None,None,None,None,None,None,None,None,None,None,831000000,None,1168000000,-1446000000,None,25922000000
2010-09-30,USD,18595000000,None,None,None,None,1027000000,2005000000,-4860000000,-596000000,None,-13854000000,1257000000,None,None,None,None,None,None,None,None,None,None,912000000,None,879000000,5998000000,None,14013000000
2009-09-30,USD,10159000000,None,None,None,None,703000000,1144000000,-939000000,54000000,None,-17434000000,663000000,None,None,None,None,None,None,None,None,None,None,475000000,None,710000000,-6612000000,None,5704000000
2008-09-30,USD,9596000000,None,None,None,None,473000000,1091000000,None,-163000000,None,-8189000000,1116000000,None,None,None,None,None,None,None,None,None,None,-124000000,None,516000000,2523000000,None,4834000000
2007-09-30,USD,5470000000,None,None,None,None,317000000,735000000,None,-76000000,None,-3249000000,739000000,None,None,None,None,None,None,None,None,None,None,-3000000,None,242000000,2960000000,None,3496000000
2006-09-30,USD,2220000000,None,None,None,None,225000000,657000000,None,-105000000,None,357000000,324000000,None,None,None,None,None,None,None,None,None,None,-355000000,None,163000000,2901000000,None,1989000000

In [80]:
df_income.to_csv("./apple/income_statement.csv")

In [81]:
df_cashflow.to_csv("./apple/cashflow_statement.csv")

In [82]:
df_balance_sheet.to_csv("./apple/balance_statement.csv")

In [58]:
url = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol=AAPL&apikey={API_key}'
appl_overview = return_json(url)

In [72]:
appl_overview_df = pd.json_normalize(appl_overview)#.T.rename(columns={0:"Values"})

In [83]:
appl_overview_df.set_index("Symbol",inplace=True)

In [84]:
appl_overview_df.to_csv("./apple/overview.csv")

In [87]:
url = 'https://www.alphavantage.co/query?function=DIVIDENDS&symbol=AAPL&apikey={API_key}'
appl_dividends = return_json(url)

In [89]:
appl_dividends_df = pd.json_normalize(appl_dividends.get("data"))

In [91]:
appl_dividends_df.to_csv("./apple/dividends.csv")

In [92]:
url = 'https://www.alphavantage.co/query?function=SPLITS&symbol=AAPL&apikey={API_key}'
appl_splits = return_json(url)

In [94]:
appl_splits_df = pd.json_normalize(appl_splits.get("data"))

In [96]:
appl_splits_df.to_csv("./apple/splits.csv")

In [99]:
url = 'https://www.alphavantage.co/query?function=SHARES_OUTSTANDING&symbol=AAPL&apikey={API_key}'
appl_shares_outstanding = return_json(url)

In [102]:
appl_shares_outstanding_df =  pd.json_normalize(appl_shares_outstanding.get("data"))

In [104]:
appl_shares_outstanding_df.to_csv("./apple/shares_outstanding.csv")

In [105]:
url = 'https://www.alphavantage.co/query?function=EARNINGS&symbol=AAPL&apikey={API_key}'
appl_earnings = return_json(url)

In [107]:
appl_earnings_df = pd.json_normalize(appl_earnings.get("annualEarnings"))

In [109]:
appl_earnings_df.to_csv("./apple/earnings.csv")

In [110]:
url = 'https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES&symbol=AAPL&apikey={API_key}'
appl_earnings_est = return_json(url)

In [112]:
appl_earnings_est_df = pd.json_normalize(appl_earnings_est.get("estimates"))

In [113]:
appl_earnings_est_df.to_csv("./apple/earnings_est.csv")

In [40]:
url = 'https://www.alphavantage.co/query?function=NEWS_SENTIMENT&tickers=AAPL&apikey={API_key}'
appl_sentiment = return_json(url)

In [41]:
appl_sentiment

{'items': '50',
 'sentiment_score_definition': 'x <= -0.35: Bearish; -0.35 < x <= -0.15: Somewhat-Bearish; -0.15 < x < 0.15: Neutral; 0.15 <= x < 0.35: Somewhat_Bullish; x >= 0.35: Bullish',
 'relevance_score_definition': '0 < x <= 1, with a higher score indicating higher relevance.',
 'feed': [{'title': 'Why Is TD Cowen Doubling Down on Amazon (AMZN), Microsoft (MSFT), and Apple (AAPL) ahead of Earnings Next Week',
   'url': 'https://www.tipranks.com/news/why-is-td-cowen-doubling-down-on-amazon-amzn-microsoft-msft-and-apple-aapl-ahead-of-earnings-next-week',
   'time_published': '20260424T153952',
   'authors': ['Radhika Saraogi'],
   'summary': "TD Cowen is bullish on Amazon, Apple, and Microsoft ahead of their upcoming earnings reports, citing accelerated AI adoption, robust cloud demand, and strong product cycles as key drivers for durable growth. The firm believes the market is underestimating the AI momentum of these Big Tech giants and foresees significant revenue streams from GenAI monetization and rising cloud workloads through 2026. Analysts reiterated Buy ratings for all three companies, highlighting specific growth factors like Microsoft's Copilot adoption, Amazon's AWS GenAI revenue from the Anthropic partnership, and Apple's strong iPhone 17 cycle and upcoming AI-powered Siri.",
   'banner_image': 'https://blog.tipranks.com/wp-content/uploads/2026/04/shutterstock_2767415937-750x406.jpg',
   'source': 'TipRanks',
   'category_within_source': 'General',
   'source_domain': 'TipRanks',
   'topics': [{'topic': 'earnings', 'relevance_score': '0.923782'},
    {'topic': 'technology', 'relevance_score': '0.802986'},
    {'topic': 'financial_markets', 'relevance_score': '0.713576'}],
   'overall_sentiment_score': 0.652583,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'COWNL',
     'relevance_score': '0.822447',
     'ticker_sentiment_score': '0.729572',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'AMZN',
     'relevance_score': '0.959899',
     'ticker_sentiment_score': '0.698182',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'MSFT',
     'relevance_score': '0.953645',
     'ticker_sentiment_score': '0.635933',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.994214',
     'ticker_sentiment_score': '0.618584',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': 'Qualcomm Inc Stock (QCOM) Moved Up by 7.81% on Apr 24: What Investors Need To Know',
   'url': 'https://www.tradingkey.com/news/market-movers/261821766-market-movers-qcom-20260424',
   'time_published': '20260424T151523',
   'authors': ['TradingKey'],
   'summary': "Qualcomm (QCOM) shares rose by 7.81% due to strategic advancements in AI-enabled PCs and automotive chips, a $20 billion share repurchase program, and the confirmation that its Snapdragon chips will power the upcoming Samsung Galaxy S27 series. These factors, combined with a positive broader market environment and anticipation of strong Q2 fiscal 2026 earnings, are driving investor optimism despite some earlier analyst caution. The company's focus on high-growth segments and commitment to shareholder value are key drivers for its current upward trajectory.",
   'banner_image': 'https://resource.tradingkey.com/uploads/20251024/68658377675a42e2bbed98144a729ddatradingkeylogo-ed79a44cf96240a287ca1bb541f06bff.png',
   'source': 'TradingKey',
   'category_within_source': 'General',
   'source_domain': 'TradingKey',
   'topics': [{'topic': 'earnings', 'relevance_score': '0.918293'},
    {'topic': 'financial_markets', 'relevance_score': '0.843551'},
    {'topic': 'technology', 'relevance_score': '0.945412'}],
   'overall_sentiment_score': 0.36289,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'QCOM',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.624587',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'AMD',
     'relevance_score': '0.603819',
     'ticker_sentiment_score': '0.438455',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'NVDA',
     'relevance_score': '0.646038',
     'ticker_sentiment_score': '0.406133',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'INTC',
     'relevance_score': '0.627221',
     'ticker_sentiment_score': '0.417531',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.747683',
     'ticker_sentiment_score': '-0.205598',
     'ticker_sentiment_label': 'Somewhat-Bearish'}]},
  {'title': 'Ceva’s 5G NTN Modem IP Could Democratize Modems for Satellite Terminals',
   'url': 'https://www.embedded.com/cevas-5g-ntn-modem-ip-could-democratize-modems-for-satellite-terminals',
   'time_published': '20260424T150957',
   'authors': ['Anton Shilov'],
   'summary': 'Ceva Inc. has introduced its PentaG-NTN modem IP subsystem, designed to simplify the development of 5G non-terrestrial network (NTN) modems for satellite terminals. This innovation aims to democratize the market for 5G NTN modems by allowing companies without prior satellite modem expertise to develop them, significantly reducing R&D costs and time to market. The technology addresses the complexities of satellite communications, such as Doppler effects and long delays, and supports the convergence of terrestrial and non-terrestrial networks.',
   'banner_image': 'https://www.embedded.com/wp-content/uploads/sites/2/2026/04/Ceva-PentaG-NTN-modem-IP-features-Fig1.jpg?w=1024',
   'source': 'Embedded-Control-Europe',
   'category_within_source': 'General',
   'source_domain': 'Embedded-Control-Europe',
   'topics': [{'topic': 'technology', 'relevance_score': '0.944824'}],
   'overall_sentiment_score': 0.182762,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'CEVA',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.467857',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'QCOM',
     'relevance_score': '0.714739',
     'ticker_sentiment_score': '-0.097896',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.608833',
     'ticker_sentiment_score': '0.117295',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Amkor's Near-Term Outlook Makes The Stock A Hold - Apple (NASDAQ:AAPL), Amkor Technology (NASDAQ:AMKR)",
   'url': 'https://www.benzinga.com/Opinion/26/04/52033089/amkor-technology-the-arizona-ai-packaging-bet-is-real-but-youre-already-paying-for-it',
   'time_published': '20260424T144239',
   'authors': ['Emmanuel Onwusah'],
   'summary': 'Amkor Technology is identified as a company with strong long-term potential due to its strategic position in the semiconductor industry and its significant investment in an Arizona packaging facility crucial for AI infrastructure. However, the author recommends a "Hold" rating for the stock in the near term because the current valuation already prices in future growth that won\'t materialize until 2028, leading to an unfavorable risk-reward profile considering projected negative free cash flow and lower margins in the interim.',
   'banner_image': 'https://cdn.benzinga.com/files/images/story/2025/07/24/article-header-background-image.png?quality=85&auto=webp&width=1300',
   'source': 'Benzinga',
   'category_within_source': 'General',
   'source_domain': 'Benzinga',
   'topics': [{'topic': 'earnings', 'relevance_score': '0.935897'},
    {'topic': 'technology', 'relevance_score': '0.830533'},
    {'topic': 'financial_markets', 'relevance_score': '0.709216'},
    {'topic': 'economy_macro', 'relevance_score': '0.620721'}],
   'overall_sentiment_score': 0.095562,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'AMKR',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '-0.252821',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.716833',
     'ticker_sentiment_score': '0.113332',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NVDA',
     'relevance_score': '0.603054',
     'ticker_sentiment_score': '0.312140',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'QCOM',
     'relevance_score': '0.567327',
     'ticker_sentiment_score': '0.157590',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'TD Cowen reiterates Buy on Apple stock, cites iPhone growth',
   'url': 'https://www.investing.com/news/analyst-ratings/td-cowen-reiterates-buy-on-apple-stock-cites-iphone-growth-93CH-4636077',
   'time_published': '20260424T143952',
   'authors': ['Investing.com'],
   'summary': 'TD Cowen has reiterated its Buy rating on Apple stock with a $325 price target, anticipating strong iPhone 17 sales and market share gains from the new MacBook Neo. Despite potential gross margin pressure from rising memory costs, the firm maintains a positive outlook, expecting Apple to meet Street revenue estimates for the March 2026 quarter. The report also highlights the upcoming leadership transition with John Ternus succeeding Tim Cook as CEO in September 2026, and mentions varying analyst sentiments following this news.',
   'banner_image': 'https://i-invdn-com.investing.com/news/news_pile_69x52._800x533_L_1419494209.jpg',
   'source': 'Investing.com',
   'category_within_source': 'General',
   'source_domain': 'Investing.com',
   'topics': [{'topic': 'earnings', 'relevance_score': '0.904390'},
    {'topic': 'financial_markets', 'relevance_score': '0.845778'},
    {'topic': 'technology', 'relevance_score': '0.727453'}],
   'overall_sentiment_score': 0.15555,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'COWNL',
     'relevance_score': '0.323265',
     'ticker_sentiment_score': '0.038006',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.982773',
     'ticker_sentiment_score': '0.328856',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Tim Cook stepping down at Apple – an era ends, a vision continues',
   'url': 'https://chainstoreage.com/tim-cook-stepping-down-apple-era-ends-vision-continues',
   'time_published': '20260424T143659',
   'authors': ['Dan Berthiaume'],
   'summary': "Tim Cook, Apple's CEO since 2011, will step down on September 1, 2026, becoming executive chairman, with John Ternus, SVP of hardware engineering, named as his successor. This transition signals continuity in Apple's strategy, emphasizing its hardware-focused approach, commitment to user-centric AI like Apple Intelligence, and preference for internal leadership in critical roles. The company's new leadership is expected to maintain its core values and development philosophy.",
   'banner_image': 'https://assets1.chainstoreage.com/images/v/max_width_1440/2026-04/john_ternus.jpg',
   'source': 'Chain Store Age',
   'category_within_source': 'General',
   'source_domain': 'Chain Store Age',
   'topics': [{'topic': 'technology', 'relevance_score': '0.812692'},
    {'topic': 'retail_wholesale', 'relevance_score': '0.649213'}],
   'overall_sentiment_score': 0.33459,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.326161',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': "Better International ETF: iShares' IEMG vs. State Street's SPGM",
   'url': 'https://www.fool.com/coverage/etfs/2026/04/24/better-international-etf-ishares-iemg-vs-state-street-s-spgm/',
   'time_published': '20260424T140129',
   'authors': ['Robert Izquierdo'],
   'summary': 'This article compares two international ETFs: State Street SPDR Portfolio MSCI Global Stock Market ETF (SPGM) and iShares Core MSCI Emerging Markets ETF (IEMG). It highlights their differences in geographic focus, sector exposure, and risk profiles, despite sharing the same low expense ratio. The comparison delves into their cost, performance, risk, and portfolio composition to help investors choose based on their strategies.',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fcdn.content.foolcdn.com%2Fimages%2F1umn9qeh%2Fproduction%2Fe2a7a839652ce1e4b5e887767e5794b4ba7e66f4-1401x1251.png%3Fw%3D800%26q%3D75%26fit%3Dmax%26auto%3Dformat&w=3840&op=resize',
   'source': 'The Motley Fool',
   'category_within_source': 'General',
   'source_domain': 'The Motley Fool',
   'topics': [{'topic': 'financial_markets', 'relevance_score': '0.948425'},
    {'topic': 'finance', 'relevance_score': '0.729644'}],
   'overall_sentiment_score': 0.281435,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'STT',
     'relevance_score': '0.734248',
     'ticker_sentiment_score': '0.233283',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'MSFT',
     'relevance_score': '0.611888',
     'ticker_sentiment_score': '0.349845',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.629171',
     'ticker_sentiment_score': '0.325711',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Weekly news roundup: Tim Cook exits Apple, Meta layoffs intensify and Anthropic investigates Claude',
   'url': 'https://www.techtarget.com/searchcio/news/366642373/Weekly-news-roundup-Tim-Cook-exits-Apple-Meta-layoffs-intensify-and-Anthropic-investigates-Claude',
   'time_published': '20260424T130927',
   'authors': ['Rosa Heaton'],
   'summary': "This weekly news roundup covers significant tech developments including Tim Cook's departure as Apple CEO, Meta's intensified layoffs and plans to use employee data for AI training, and Anthropic's investigation into a breach of its Claude Mythos model. The article also highlights new AI model releases from OpenAI and DeepSeek, alongside updates on executive changes at Apple and LinkedIn, and recent IPO listings.",
   'banner_image': 'https://www.techtarget.com/rms/onlineimages/maze_g467037520_searchsitetablet_520X173.jpg',
   'source': 'TechTarget',
   'category_within_source': 'General',
   'source_domain': 'TechTarget',
   'topics': [{'topic': 'ipo', 'relevance_score': '0.933735'},
    {'topic': 'technology', 'relevance_score': '0.947779'},
    {'topic': 'finance', 'relevance_score': '0.639520'}],
   'overall_sentiment_score': -0.104799,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'TTGT',
     'relevance_score': '0.328864',
     'ticker_sentiment_score': '0.015342',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.998247',
     'ticker_sentiment_score': '0.122038',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'META',
     'relevance_score': '0.925759',
     'ticker_sentiment_score': '-0.295359',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'MSFT',
     'relevance_score': '0.791407',
     'ticker_sentiment_score': '-0.222844',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'GOOGL',
     'relevance_score': '0.593046',
     'ticker_sentiment_score': '0.081624',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Will Edison International’s Board Refresh Accelerate Its AI and Digital Ambitions?',
   'url': 'https://futurumgroup.com/insights/will-edison-internationals-board-refresh-accelerate-its-ai-and-digital-ambitions/',
   'time_published': '20260424T121026',
   'authors': ['FuturumAI'],
   'summary': 'Edison International has appointed M. Susan Hardwick as an independent director to its boards, signaling a strategic move to accelerate its AI and digital transformation efforts. This decision comes as the utility industry faces significant pressure to modernize operations, manage grid constraints, and leverage advanced AI solutions to enhance efficiency and service. The company aims to address potential inertia and execution risks associated with traditionally slow-moving utility sectors by bringing in experienced leadership dedicated to driving digital innovation and partnerships with technology vendors.',
   'banner_image': 'https://futurumgroup.com/wp-content/uploads/2026/04/FuturumAI-150x150.png.webp',
   'source': 'The Futurum Group',
   'category_within_source': 'General',
   'source_domain': 'The Futurum Group',
   'topics': [{'topic': 'technology', 'relevance_score': '0.827163'},
    {'topic': 'energy_transportation', 'relevance_score': '0.724897'}],
   'overall_sentiment_score': 0.168767,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'EIX',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.251383',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'MSFT',
     'relevance_score': '0.634029',
     'ticker_sentiment_score': '0.134777',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOGL',
     'relevance_score': '0.576272',
     'ticker_sentiment_score': '0.113681',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'QCOM',
     'relevance_score': '0.552676',
     'ticker_sentiment_score': '0.120575',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.570852',
     'ticker_sentiment_score': '0.126787',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Rakuten Securities Inc. Has $804,000 Stock Holdings in The Walt Disney Company $DIS',
   'url': 'https://www.marketbeat.com/instant-alerts/filing-rakuten-securities-inc-has-804000-stock-holdings-in-the-walt-disney-company-dis-2026-04-24/',
   'time_published': '20260424T120727',
   'authors': ['MarketBeat'],
   'summary': 'Rakuten Securities Inc. significantly increased its stake in The Walt Disney Company (NYSE:DIS) during the fourth quarter, boosting its holdings by 474.2% to 7,069 shares valued at $804,000. This increase follows Disney\'s Q4 earnings exceeding estimates with an EPS of $1.63 and revenue of $25.98 billion. Analysts maintain a "Moderate Buy" rating for Disney, with an average price target of $133.53.',
   'banner_image': 'https://www.marketbeat.com/logos/the-walt-disney-company-logo-1200x675.png?v=20201229105326',
   'source': 'MarketBeat',
   'category_within_source': 'General',
   'source_domain': 'MarketBeat',
   'topics': [{'topic': 'earnings', 'relevance_score': '0.908935'},
    {'topic': 'financial_markets', 'relevance_score': '0.908476'}],
   'overall_sentiment_score': 0.222371,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'DIS',
     'relevance_score': '1.000000',
     'ticker_sentiment_score': '0.326518',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.619440',
     'ticker_sentiment_score': '0.107479',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Warner Financial Inc. Acquires 6,566 Shares of Apple Inc. $AAPL',
   'url': 'https://www.marketbeat.com/instant-alerts/filing-warner-financial-inc-acquires-6566-shares-of-apple-inc-aapl-2026-04-24/',
   'time_published': '20260424T120658',
   'authors': ['MarketBeat'],
   'summary': "Warner Financial Inc. increased its stake in Apple Inc. by 56% in the fourth quarter, acquiring an additional 6,566 shares to bring its total holding to 18,293 shares worth approximately $4.97 million. Apple accounts for 1.7% of Warner Financial Inc.'s investment portfolio. The article also details Apple's strong financial performance, reporting $2.84 EPS against a $2.67 consensus and $143.76 billion in revenue, along with key insider stock sales by SVP Deirdre O'Brien and CEO Tim Cook.",
   'banner_image': 'https://www.marketbeat.com/logos/apple-inc-logo-1200x675.png',
   'source': 'MarketBeat',
   'category_within_source': 'General',
   'source_domain': 'MarketBeat',
   'topics': [{'topic': 'earnings', 'relevance_score': '0.916094'},
    {'topic': 'financial_markets', 'relevance_score': '0.835161'},
    {'topic': 'technology', 'relevance_score': '0.720249'}],